// Generated by gencpp from file iris_ir_sitl/InfraredDetection.msg
// DO NOT EDIT!


#ifndef IRIS_IR_SITL_MESSAGE_INFRAREDDETECTION_H
#define IRIS_IR_SITL_MESSAGE_INFRAREDDETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iris_ir_sitl
{
template <class ContainerAllocator>
struct InfraredDetection_
{
  typedef InfraredDetection_<ContainerAllocator> Type;

  InfraredDetection_()
    : receiver_id()
    , detected_ids()
    , distances()
    , strengths()
    , timestamp(0.0)  {
    }
  InfraredDetection_(const ContainerAllocator& _alloc)
    : receiver_id(_alloc)
    , detected_ids(_alloc)
    , distances(_alloc)
    , strengths(_alloc)
    , timestamp(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _receiver_id_type;
  _receiver_id_type receiver_id;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _detected_ids_type;
  _detected_ids_type detected_ids;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _distances_type;
  _distances_type distances;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _strengths_type;
  _strengths_type strengths;

   typedef double _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> const> ConstPtr;

}; // struct InfraredDetection_

typedef ::iris_ir_sitl::InfraredDetection_<std::allocator<void> > InfraredDetection;

typedef boost::shared_ptr< ::iris_ir_sitl::InfraredDetection > InfraredDetectionPtr;
typedef boost::shared_ptr< ::iris_ir_sitl::InfraredDetection const> InfraredDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iris_ir_sitl::InfraredDetection_<ContainerAllocator1> & lhs, const ::iris_ir_sitl::InfraredDetection_<ContainerAllocator2> & rhs)
{
  return lhs.receiver_id == rhs.receiver_id &&
    lhs.detected_ids == rhs.detected_ids &&
    lhs.distances == rhs.distances &&
    lhs.strengths == rhs.strengths &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iris_ir_sitl::InfraredDetection_<ContainerAllocator1> & lhs, const ::iris_ir_sitl::InfraredDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iris_ir_sitl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16244eb9ef16a053d5fdf4543baba6bc";
  }

  static const char* value(const ::iris_ir_sitl::InfraredDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16244eb9ef16a053ULL;
  static const uint64_t static_value2 = 0xd5fdf4543baba6bcULL;
};

template<class ContainerAllocator>
struct DataType< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iris_ir_sitl/InfraredDetection";
  }

  static const char* value(const ::iris_ir_sitl::InfraredDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string receiver_id\n"
"string[] detected_ids\n"
"float64[] distances\n"
"float64[] strengths\n"
"float64 timestamp\n"
;
  }

  static const char* value(const ::iris_ir_sitl::InfraredDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.receiver_id);
      stream.next(m.detected_ids);
      stream.next(m.distances);
      stream.next(m.strengths);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InfraredDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iris_ir_sitl::InfraredDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iris_ir_sitl::InfraredDetection_<ContainerAllocator>& v)
  {
    s << indent << "receiver_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.receiver_id);
    s << indent << "detected_ids[]" << std::endl;
    for (size_t i = 0; i < v.detected_ids.size(); ++i)
    {
      s << indent << "  detected_ids[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.detected_ids[i]);
    }
    s << indent << "distances[]" << std::endl;
    for (size_t i = 0; i < v.distances.size(); ++i)
    {
      s << indent << "  distances[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distances[i]);
    }
    s << indent << "strengths[]" << std::endl;
    for (size_t i = 0; i < v.strengths.size(); ++i)
    {
      s << indent << "  strengths[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.strengths[i]);
    }
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRIS_IR_SITL_MESSAGE_INFRAREDDETECTION_H
