// Generated by gencpp from file iris_ir_sitl/InfraredSignal.msg
// DO NOT EDIT!


#ifndef IRIS_IR_SITL_MESSAGE_INFRAREDSIGNAL_H
#define IRIS_IR_SITL_MESSAGE_INFRAREDSIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iris_ir_sitl
{
template <class ContainerAllocator>
struct InfraredSignal_
{
  typedef InfraredSignal_<ContainerAllocator> Type;

  InfraredSignal_()
    : sender_id()
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , strength(0.0)
    , timestamp(0.0)  {
    }
  InfraredSignal_(const ContainerAllocator& _alloc)
    : sender_id(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , strength(0.0)
    , timestamp(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _sender_id_type;
  _sender_id_type sender_id;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _strength_type;
  _strength_type strength;

   typedef double _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> const> ConstPtr;

}; // struct InfraredSignal_

typedef ::iris_ir_sitl::InfraredSignal_<std::allocator<void> > InfraredSignal;

typedef boost::shared_ptr< ::iris_ir_sitl::InfraredSignal > InfraredSignalPtr;
typedef boost::shared_ptr< ::iris_ir_sitl::InfraredSignal const> InfraredSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iris_ir_sitl::InfraredSignal_<ContainerAllocator1> & lhs, const ::iris_ir_sitl::InfraredSignal_<ContainerAllocator2> & rhs)
{
  return lhs.sender_id == rhs.sender_id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.strength == rhs.strength &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iris_ir_sitl::InfraredSignal_<ContainerAllocator1> & lhs, const ::iris_ir_sitl::InfraredSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iris_ir_sitl

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4bfc02816f81c84155a6b91d14604f20";
  }

  static const char* value(const ::iris_ir_sitl::InfraredSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4bfc02816f81c841ULL;
  static const uint64_t static_value2 = 0x55a6b91d14604f20ULL;
};

template<class ContainerAllocator>
struct DataType< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iris_ir_sitl/InfraredSignal";
  }

  static const char* value(const ::iris_ir_sitl::InfraredSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender_id\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 strength\n"
"float64 timestamp\n"
;
  }

  static const char* value(const ::iris_ir_sitl::InfraredSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender_id);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.strength);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InfraredSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iris_ir_sitl::InfraredSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iris_ir_sitl::InfraredSignal_<ContainerAllocator>& v)
  {
    s << indent << "sender_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.sender_id);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "strength: ";
    Printer<double>::stream(s, indent + "  ", v.strength);
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IRIS_IR_SITL_MESSAGE_INFRAREDSIGNAL_H
