// Generated by gencpp from file drone_infrared_system/InfraredSignal.msg
// DO NOT EDIT!


#ifndef DRONE_INFRARED_SYSTEM_MESSAGE_INFRAREDSIGNAL_H
#define DRONE_INFRARED_SYSTEM_MESSAGE_INFRAREDSIGNAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>

namespace drone_infrared_system
{
template <class ContainerAllocator>
struct InfraredSignal_
{
  typedef InfraredSignal_<ContainerAllocator> Type;

  InfraredSignal_()
    : header()
    , robot_name()
    , transmission_power(0.0)
    , wavelength(0.0)
    , source_pose()
    , received_power(0.0)
    , estimated_distance(0.0)
    , emitter_id()  {
    }
  InfraredSignal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_name(_alloc)
    , transmission_power(0.0)
    , wavelength(0.0)
    , source_pose(_alloc)
    , received_power(0.0)
    , estimated_distance(0.0)
    , emitter_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_name_type;
  _robot_name_type robot_name;

   typedef double _transmission_power_type;
  _transmission_power_type transmission_power;

   typedef double _wavelength_type;
  _wavelength_type wavelength;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _source_pose_type;
  _source_pose_type source_pose;

   typedef double _received_power_type;
  _received_power_type received_power;

   typedef double _estimated_distance_type;
  _estimated_distance_type estimated_distance;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _emitter_id_type;
  _emitter_id_type emitter_id;





  typedef boost::shared_ptr< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> const> ConstPtr;

}; // struct InfraredSignal_

typedef ::drone_infrared_system::InfraredSignal_<std::allocator<void> > InfraredSignal;

typedef boost::shared_ptr< ::drone_infrared_system::InfraredSignal > InfraredSignalPtr;
typedef boost::shared_ptr< ::drone_infrared_system::InfraredSignal const> InfraredSignalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_infrared_system::InfraredSignal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drone_infrared_system::InfraredSignal_<ContainerAllocator1> & lhs, const ::drone_infrared_system::InfraredSignal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_name == rhs.robot_name &&
    lhs.transmission_power == rhs.transmission_power &&
    lhs.wavelength == rhs.wavelength &&
    lhs.source_pose == rhs.source_pose &&
    lhs.received_power == rhs.received_power &&
    lhs.estimated_distance == rhs.estimated_distance &&
    lhs.emitter_id == rhs.emitter_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drone_infrared_system::InfraredSignal_<ContainerAllocator1> & lhs, const ::drone_infrared_system::InfraredSignal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drone_infrared_system

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "229d00d508a2c64dc70d2cc763410fb1";
  }

  static const char* value(const ::drone_infrared_system::InfraredSignal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x229d00d508a2c64dULL;
  static const uint64_t static_value2 = 0xc70d2cc763410fb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_infrared_system/InfraredSignal";
  }

  static const char* value(const ::drone_infrared_system::InfraredSignal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string robot_name\n"
"float64 transmission_power\n"
"float64 wavelength\n"
"geometry_msgs/Pose source_pose\n"
"float64 received_power\n"
"float64 estimated_distance\n"
"string emitter_id\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::drone_infrared_system::InfraredSignal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_name);
      stream.next(m.transmission_power);
      stream.next(m.wavelength);
      stream.next(m.source_pose);
      stream.next(m.received_power);
      stream.next(m.estimated_distance);
      stream.next(m.emitter_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InfraredSignal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_infrared_system::InfraredSignal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_infrared_system::InfraredSignal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_name);
    s << indent << "transmission_power: ";
    Printer<double>::stream(s, indent + "  ", v.transmission_power);
    s << indent << "wavelength: ";
    Printer<double>::stream(s, indent + "  ", v.wavelength);
    s << indent << "source_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.source_pose);
    s << indent << "received_power: ";
    Printer<double>::stream(s, indent + "  ", v.received_power);
    s << indent << "estimated_distance: ";
    Printer<double>::stream(s, indent + "  ", v.estimated_distance);
    s << indent << "emitter_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.emitter_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_INFRARED_SYSTEM_MESSAGE_INFRAREDSIGNAL_H
